export const RankTable: { [x: string]: string } = {
  UNRANKED: '!bg-gray-100 !text-gray-800',
  'IRON 1': '!bg-ctp-surface0 !text-ctp-subtext1',
  'IRON 2': '!bg-ctp-surface0 !text-ctp-subtext1',
  'IRON 3': '!bg-ctp-surface0 !text-ctp-subtext1',
  'BRONZE 1': '!bg-ctp-peach !text-ctp-crust',
  'BRONZE 2': '!bg-ctp-peach !text-ctp-crust',
  'BRONZE 3': '!bg-ctp-peach !text-ctp-crust',
  'SILVER 1': '!bg-gray-100 !text-gray-800',
  'SILVER 2': '!bg-gray-100 !text-gray-800',
  'SILVER 3': '!bg-gray-100 !text-gray-800',
  'GOLD 1': '!bg-ctp-yellow !text-ctp-crust',
  'GOLD 2': '!bg-ctp-yellow !text-ctp-crust',
  'GOLD 3': '!bg-ctp-yellow !text-ctp-crust',
  'PLATINUM 1': '!bg-ctp-teal !text-ctp-crust',
  'PLATINUM 2': '!bg-ctp-teal !text-ctp-crust',
  'PLATINUM 3': '!bg-ctp-teal !text-ctp-crust',
  'DIAMOND 1': '!bg-ctp-mauve !text-ctp-crust',
  'DIAMOND 2': '!bg-ctp-mauve !text-ctp-crust',
  'DIAMOND 3': '!bg-ctp-mauve !text-ctp-crust',
  'ASCENDANT 1': '!bg-ctp-green !text-ctp-crust',
  'ASCENDANT 2': '!bg-ctp-green !text-ctp-crust',
  'ASCENDANT 3': '!bg-ctp-green !text-ctp-crust',
  'IMMORTAL 1': '!bg-ctp-red !text-ctp-crust',
  'IMMORTAL 2': '!bg-ctp-red !text-ctp-crust',
  'IMMORTAL 3': '!bg-ctp-red !text-ctp-crust',
  RADIANT: '!bg-ctp-yellow !text-ctp-crust',
}
